---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "rabbitmq"
  namespace: "default"
  labels:
    app: "rabbitmq"
spec:
  ports:
  - protocol: "TCP"
    port: 5672
  selector:
    app: "rabbitmq"
  type: "LoadBalancer"
  loadBalancerIP: ""
